### ISSUE TITLE
Conflicts with crosswalk

### ISSUE THREAD

**Issue by xqyww123** [GetuiLaboratory/cordova-plugin-getuisdk#13]
After removing `getuisdk` or `cross-walk` everything works

For android platform, testing on Mac OSX

Following error occurred ：

```
To run dex in process, the Gradle daemon needs a larger heap.
It currently has approximately 910 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to more than 2048 MB.
To do this set org.gradle.jvmargs=-Xmx2048M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html

Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    	at com.android.dx.command.dexer.Main.run(Main.java:277)

    	at com.android.dx.command.dexer.Main.main(Main.java:245)
    	at com.android.dx.command.Main.main(Main.java:106)


:transformClassesWithDexForArmv7Debug FAILED



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
>
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
 option to get more log output.


BUILD FAILED

Total time: 42.991 secs

Error: /Users/Hao/Project/cordova/argassistant/platforms/android/gradlew: Command failed with exit code 1 Error output:
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    	at com.android.dx.command.dexer.Main.run(Main.java:277)
    	at com.android.dx.command.dexer.Main.main(Main.java:245)
    	at com.android.dx.command.Main.main(Main.java:106)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by fenglu09** [comment]
you should  remove the `support-v4` package in getui plugin。

**Comment by xqyww123** [comment]
yeah @fenglu09, you are right. There are three location need to modify :

**Comment by xqyww123** [comment]
And I think that isn't duty for GeTui, but crosswalk.

**Comment by fenglu09** [comment]
Yes. And you have to pay attention when use GeTui in iOS.  you will meet several issues.

**Comment by fenglu09** [comment]
such as, you cannot receive payload message on iOS.
