### ISSUE TITLE
Multiple dex files define  error

### ISSUE THREAD

**Issue by fenglu09** [GetuiLaboratory/cordova-plugin-getuisdk#4]
今天安装了 `de.appplant.cordova.plugin.local-notification` 插件后，再编译的时候就出现了这个问题。
如果至安装其中的一个编译不会出错。
```
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

```
cordova 版本： 6.1.1
其他插件： 
```
cordova-android-support-v4 4.0.0 "Android Support v4"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.1.1-dev "Geolocation"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.1.1 "InAppBrowser"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-whitelist 1.2.0 "Whitelist"
cordova-plugin-x-toast 2.5.0 "Toast"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
```

**Comment by fenglu09** [comment]
没人回答。。。
最后把个推插件里面的 ` android-support-v4.jar` 删除就好了
